version: '3.8'

services:
  #nginx:
  #  image: nginx
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
  #  depends_on:
  #    - relay
  relay:
    container_name: relay
    build: .
    ports:
      - "8008:7447"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: example
      DB_NAME: postgres
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"